version: '3.6'

services: 

  # backend API
  smart-brain-api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-branin-api
    environment: 
      POSTGRES_URI: postgres://bombay:secret@postgres:5432/smart-brain-docker
    links:
        - postgres
    ports: 
      - "3001:3001"


  # postgres
  postgres:
    environment: 
      POSTGRES_USER: bombay
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports: 
      - "5432:5432" 
  
